name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build:vite
        env:
          NODE_ENV: production

      - name: Build and Release Electron
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
        env:
          # Para que electron-builder sepa que estamos en producción
          NODE_ENV: production
